# Generated by Django 4.2.2 on 2024-01-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="spotify_auth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="spotify_email",
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_refresh",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
