# Generated by Django 4.2.2 on 2023-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
