# Generated by Django 4.2.11 on 2024-06-09 03:26

from django.db import migrations, models

def update_admin_log(apps, schema_editor):
    # Get the models
    User = apps.get_model('user', 'User')
    AdminLog = apps.get_model('admin', 'LogEntry')

    # Update foreign key field to point to the correct table
    for log_entry in AdminLog.objects.all():
        try:
            user = User.objects.get(id=log_entry.user_id)
            log_entry.user_id = user.id
            log_entry.save()
        except User.DoesNotExist:
            # Handle case where the user does not exist
            log_entry.user_id = None
            log_entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),  # Replace with the last migration file in 'user'
    ]

    operations = [
        migrations.RunPython(update_admin_log),
    ]
