# Generated by Django 4.2.2 on 2024-01-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_spotify_auth_remove_user_spotify_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_access",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_expires_in",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
