# Generated by Django 4.2.2 on 2023-09-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="spotify_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
