# Generated by Django 4.2.2 on 2024-01-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_spotify_access_user_spotify_expires_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="spotify_expires_in",
        ),
        migrations.AddField(
            model_name="user",
            name="spotify_expires_at",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
