# Generated by Django 4.2.2 on 2024-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_created_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
