# Generated by Django 4.2.2 on 2024-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_email_verified_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
