# Generated by Django 4.2.2 on 2024-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="xp",
            field=models.IntegerField(default=0),
        ),
    ]
