# Generated by Django 4.2.2 on 2024-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_tokens_user_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
