# Generated by Django 4.2.2 on 2024-04-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_genre_rename_username_user_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
