# Generated by Django 4.2.2 on 2024-04-11 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_user_profession"),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='xp',
            new_name='karma',
        ),
    ]
