# Generated by Django 4.2.2 on 2024-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
