# Generated by Django 3.2 on 2023-07-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='to_detect',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='to_license',
            field=models.BooleanField(null=True),
        ),
    ]
