# Generated by Django 3.2 on 2023-07-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20230727_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='to_license',
            field=models.BooleanField(default=False),
        ),
    ]
