# Generated by Django 4.2.2 on 2024-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(),
        ),
    ]
