# Generated by Django 4.2.2 on 2024-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_alter_playlist_name_alter_playlist_spotify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(max_length=255),
        ),
    ]
