# Generated by Django 4.2.2 on 2024-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0004_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(to="playlists.song"),
        ),
    ]
