# Generated by Django 4.2.2 on 2024-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0005_playlist_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artists",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
