# Generated by Django 4.2.2 on 2024-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0006_song_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
