# Generated by Django 4.2.2 on 2024-02-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0007_song_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.CharField(default=""),
        ),
    ]
