# Generated by Django 4.2.2 on 2024-02-10 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0010_song_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="image",
        ),
    ]
