# Generated by Django 4.2.2 on 2024-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0011_remove_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
