# Generated by Django 4.2.2 on 2024-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0013_playlistsong"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="snapshot_id",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
