# Generated by Django 4.2.2 on 2024-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0014_playlist_snapshot_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlistsong",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="playlistsong",
            unique_together={("playlist", "song")},
        ),
    ]
