# Generated by Django 4.2.2 on 2024-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0015_alter_playlistsong_options_playlistsong_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artists",
            field=models.JSONField(),
        ),
    ]
