# Generated by Django 4.2.2 on 2024-04-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
