# Generated by Django 4.2.2 on 2024-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_pricingpackage_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingpackage",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="pricingpackage",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Lower numbers display first."
            ),
        ),
    ]
