# Generated by Django 4.2.2 on 2024-04-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_pricingpackage_options_pricingpackage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="price",
            field=models.IntegerField(),
        ),
    ]
