# Generated by Django 4.2.2 on 2024-02-16 20:27

from django.db import migrations, models
import songquest.recommendations.models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_recommendationrequest_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationrequest",
            name="limit",
            field=models.IntegerField(
                blank=True,
                default=20,
                null=True,
                validators=[songquest.recommendations.models.validate_limit],
            ),
        ),
    ]
